# Inspired by https://dracoblue.net/dev/uploading-snapshots-and-releases-to-maven-central-with-travis/

# TODO: migrate to 11
#
language: java
jdk:
  - openjdk8

script:
  - .travis/deploy.sh

cache:
  directories:
    - $HOME/.m2

